@baseUrl = http://localhost:5068/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiN2I2ZWE0Yi04MWNkLTRhZTktYjRjNi1jMDI4MTFiODU3MzgiLCJqdGkiOiIyNzBjYzk5NC0wOGQ4LTRiZjgtYThkOS0zZTc0OGVkZDU0NDEiLCJpYXQiOjE3NDY5OTY4MDIsInJvbGUiOiJSZWNydWl0ZXIiLCJuYW1laWQiOiJiN2I2ZWE0Yi04MWNkLTRhZTktYjRjNi1jMDI4MTFiODU3MzgiLCJuYmYiOjE3NDY5OTY4MDIsImV4cCI6MTc0NzYwMTYwMiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDY4L2FwaSIsImF1ZCI6InlvdXItY2xpZW50LWFwcCJ9.dVwPsk3k75SlmlzY-qNI7g7EWeOA009o8400o4742Fk

### Register new recruiter
POST {{baseUrl}}/recruiters
Content-Type: application/json

{
  "email": "recruiter12335@example.com",
  "password": "RecruiterPass"
}

### Login recruiter
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "recruiter12335@example.com",
  "password": "RecruiterPass"
}

### Update recruiter
PUT {{baseUrl}}/recruiters/962eb2d3-a60a-4be2-baa2-ddbf57c3c7ef
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "firstName": "First name recruiter",
  "lastName": "Last name recruiter",
  "phoneNumber": "838hoe38y9",
  "company": "company",
  "notes": "my notes agdugf;dsbgsidgbsi;gbisg;sdgbygv"
}

### Reset password
POST {{baseUrl}}/recruiters/reset-password
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "userId": "b7b6ea4b-81cd-4ae9-b4c6-c02811b85738",
  "password": "newpass"
}

### Delete recruiter
DELETE {{baseUrl}}/recruiters/3dc19933-c496-4f9c-8a3c-e63c5bd1c9dd
Authorization: Bearer {{token}}
Accept: application/json

### Create vacancy
POST {{baseUrl}}/vacancies
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "Title": "First Vacancy",
  "Description": "First vacancy created by recruiter",
  "Salary": 3214,
  "Requirements": "Nothing really",
  "CompanyWebsite": "https://example.com",
  "TypeOfJob": "2",
  "Location": "1",
  "Country": "Latina",
  "RecruiterId": "b7b6ea4b-81cd-4ae9-b4c6-c02811b85738"
}

### Get recruiter vacancies
GET {{baseUrl}}/recruiters/vacancies
Authorization: Bearer {{token}}
Accept: : application/json
Content-Type: application/json