@baseUrl = http://localhost:5068/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1MjgxZDkwMi1jOTc2LTRlZjAtODI2MS1hMjM5NDJjNDE0NjQiLCJqdGkiOiJhMGZlYzVlYi05NGEwLTQ0YWQtYWNhMi0wNWYyNzE4ODFlYzUiLCJpYXQiOjE3NDQ0Nzg5NzQsInJvbGUiOiJVc2VyIiwibmJmIjoxNzQ0NDc4OTc0LCJleHAiOjE3NDUwODM3NzQsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTA2OC9hcGkiLCJhdWQiOiJ5b3VyLWNsaWVudC1hcHAifQ.vcL6icxHvgkKYAqEZZkrCPGL-LkvBQ7vDRdSUpSuJKM

### Register new user
# @name register
POST {{baseUrl}}/users
Content-Type: application/json

{
  "email": "user12@example.com",
  "password": "YourPassword123"
}

### Login user
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user1@example.com",
  "password": "YourPassword123updated"
}

### Update user
PUT {{baseUrl}}/users/5281d902-c976-4ef0-8261-a23942c41464
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "FirstName": "newFirstName",
  "LastName": "newLastName",
  "Role": "newUpdatedRole",
  "Skills": "some new skills, old skills are gone",
  "Location": "China number one",
  "YearsOfExperience": "228",
  "EnglishLevel": "5"
}

### Reset password
POST {{baseUrl}}/users/reset-password
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "userId": "5281d902-c976-4ef0-8261-a23942c41464",
  "password": "YourPassword123updated"
}

### Get user's applications
GET {{baseUrl}}/users/5281d902-c976-4ef0-8261-a23942c41464/applications
Authorization: Bearer {{token}}
Accept: application/json

### Get user's chats
GET {{baseUrl}}/users/5281d902-c976-4ef0-8261-a23942c41464/chats
Authorization: Bearer {{token}}
Accept: application/json

### Post an application
POST {{baseUrl}}/applications
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "userId": "5281d902-c976-4ef0-8261-a23942c41464",
  "vacancyId": ""
}