@baseUrl = http://localhost:5068/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1MjgxZDkwMi1jOTc2LTRlZjAtODI2MS1hMjM5NDJjNDE0NjQiLCJqdGkiOiIwOGE2Zjk0Yy1jMDE3LTRiNTAtOWFjOS02MGRkNDU0ZDdhZDMiLCJpYXQiOjE3NDY5NzQ2NTIsInJvbGUiOiJVc2VyIiwibmFtZWlkIjoiNTI4MWQ5MDItYzk3Ni00ZWYwLTgyNjEtYTIzOTQyYzQxNDY0IiwibmJmIjoxNzQ2OTc0NjUyLCJleHAiOjE3NDc1Nzk0NTIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTA2OC9hcGkiLCJhdWQiOiJ5b3VyLWNsaWVudC1hcHAifQ.msQlkcuNjSWtgerVGa3wr2duZtlmMCrKUMDXI2sshb0

### Retrieve all vacancies
GET {{baseUrl}}/vacancies
Authorization: Bearer {{token}}
Accept: application/json

### Retrieve vacancy by id
GET {{baseUrl}}/vacancies/IDHERE
Authorization: Bearer {{token}}
Accept: application/json

### Create vacancy
POST {{baseUrl}}/vacancies
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "Title": "Cool vacancy title",
  "Description": "Cool vacancy description",
  "Salary": 1233,
  "Requirements": "Cool requirements",
  "CompanyWebsite": "https://natribu.org",
  "TypeOfJob": "2",
  "Location": "1",
  "Country": "Armenia",
  "RecruiterId": "",
  "Benefits": "Nothing"
}

### Update vacancy
PUT {{baseUrl}}/vacancies/IDHERE
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "Description": "New not so cool vacancy description",
  "Salary": 1233,
  "Requirements": "New not so cool requirements",
  "CompanyWebsite": "https://natribu.org",
  "TypeOfJob": "3",
  "Location": "3",
  "VacancyId": "IDHERE",
  "Benefits": "Still nothing new"
}

### Delete vacancy
DELETE {{baseUrl}}/vacancies/IDHERE
Authorization: Bearer {{token}}
Accept: application/json

### Get applications for the vacancy
GET {{baseUrl}}/vacancies/IDHERE/applications
Authorization: Bearer {{token}}
Accept: application/json